version: "3.1"

services: 
  js_pro:
    build: .
    container_name: js_pro
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports: 
      - 8080:8080
      - 9229:9229
      - 1234:1234
      - 34539:34539
    environment:
      - COMMAND=${COMMAND}